name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.19.0"
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint -- --fix
      - run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm run start-prod
          command: npm run test:e2e
          wait-on: http://localhost:5000
  deploy:
    name: Deploy app
    runs-on: ubuntu-20.04
    needs: simple_deployment_pipeline
    if: github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip')
    steps:
      - name: Deploy to production
        id: deploy
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}

  tag_release:
    name: Tag release
    runs-on: ubuntu-20.04
    needs: deploy
    if: github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip')
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@a2c70ae13a881faf2b4953baaa9e49731997ab36
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

  notify_discord_deploy:
    runs-on: ubuntu-20.04
    needs: deploy
    steps:
      - name: Send Discord notification on success
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ success() }}
        with:
          severity: info
          description: to https://pokeman-service.onrender.com/
          details: Deployment Succeeded!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
      - name: Send Discord notification on failure
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ failure() }}
        with:
          severity: error
          description:
            Build failed for commit [${GITHUB_SHA::8}](${{ github.event.compare }})
            **Commit details:**
            - **Message:** ${github.event.commits[0].message}
            - **Committer:** ${github.event.commits[0].committer.name}
            - **Commit date:** ${github.event.commits[0].timestamp}
          details: Build failed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}

  notify_discord_simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    needs: simple_deployment_pipeline
    steps:
      - name: Send Discord notification on failure
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ failure() }}
        with:
          severity: error
          description:
            Build failed for commit [${GITHUB_SHA::8}](${{ github.event.compare }})
            **Commit details:**
            - **Message:** ${github.event.commits[0].message}
            - **Committer:** ${github.event.commits[0].committer.name}
            - **Commit date:** ${github.event.commits[0].timestamp}
          details: Build failed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
# useless with push while using render.. could be maybe edited on another file to check outside pushing
# health_check:
#    name: Healthcheck
#    runs-on: ubuntu-20.04
#    needs: deploy
#    steps:
#      - name: Check the deployed service URL
#        uses: jtalk/url-health-check-action@v3
#        with:
#          url: https://pokeman-service.onrender.com/health
#          max-attempts: 3
#         retry-delay: 5s
